/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.snapshop.form;

import com.snapshop.util.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class CustomerMgm extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMgm
     */
    public CustomerMgm() {
        initComponents();

        customerTable.getTableHeader().setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 13));
        loadCustomerData();
    }

    private void loadCustomerData() {
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        model.setRowCount(0); // Clear the table before loading data

        String query = "SELECT customerId, username, password, phone, address FROM customer";

        try (Connection connection = DatabaseConnection.getConnection(); PreparedStatement statement = connection.prepareStatement(query); ResultSet resultSet = statement.executeQuery()) {

            // Add each customer row to the table model
            while (resultSet.next()) {
                int Id = resultSet.getInt("customerId");
                String username = resultSet.getString("username");
                String password = resultSet.getString("password");
                String phone = resultSet.getString("phone");
                String address = resultSet.getString("address");

                model.addRow(new Object[]{Id, username, password, phone, address});
            }

        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to load customer data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        customerMgm1 = new javax.swing.JButton();
        customerMgm2 = new javax.swing.JButton();
        customerMgm3 = new javax.swing.JButton();

        customerTable.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "username", "password", "phone", "address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerTable.setRowHeight(30);
        jScrollPane1.setViewportView(customerTable);
        if (customerTable.getColumnModel().getColumnCount() > 0) {
            customerTable.getColumnModel().getColumn(0).setMinWidth(30);
            customerTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            customerTable.getColumnModel().getColumn(0).setMaxWidth(30);
            customerTable.getColumnModel().getColumn(1).setMinWidth(70);
            customerTable.getColumnModel().getColumn(1).setPreferredWidth(70);
            customerTable.getColumnModel().getColumn(1).setMaxWidth(70);
            customerTable.getColumnModel().getColumn(2).setMinWidth(140);
            customerTable.getColumnModel().getColumn(2).setPreferredWidth(140);
            customerTable.getColumnModel().getColumn(2).setMaxWidth(140);
            customerTable.getColumnModel().getColumn(3).setMinWidth(140);
            customerTable.getColumnModel().getColumn(3).setPreferredWidth(140);
            customerTable.getColumnModel().getColumn(3).setMaxWidth(140);
        }

        jPanel1.setOpaque(false);

        deleteBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(153, 0, 0));
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.setBorderPainted(false);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.setFocusPainted(false);
        deleteBtn.setFocusable(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        customerMgm1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        customerMgm1.setForeground(new java.awt.Color(0, 102, 102));
        customerMgm1.setText("Update");
        customerMgm1.setBorder(null);
        customerMgm1.setBorderPainted(false);
        customerMgm1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerMgm1.setFocusPainted(false);
        customerMgm1.setFocusable(false);

        customerMgm2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        customerMgm2.setForeground(new java.awt.Color(153, 0, 0));
        customerMgm2.setText("Suspend");
        customerMgm2.setBorder(null);
        customerMgm2.setBorderPainted(false);
        customerMgm2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerMgm2.setFocusPainted(false);
        customerMgm2.setFocusable(false);

        customerMgm3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        customerMgm3.setForeground(new java.awt.Color(0, 102, 102));
        customerMgm3.setText("Activate");
        customerMgm3.setBorder(null);
        customerMgm3.setBorderPainted(false);
        customerMgm3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerMgm3.setFocusPainted(false);
        customerMgm3.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerMgm3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(customerMgm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerMgm2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(customerMgm3)
                .addGap(18, 18, 18)
                .addComponent(customerMgm1)
                .addGap(18, 18, 18)
                .addComponent(customerMgm2)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        // Check if a row is selected
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a customer to delete.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirm deletion
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete the selected customer?",
                "Confirm Deletion",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        // Get the customerId of the selected row
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        int customerId = (int) model.getValueAt(selectedRow, 0); // Assuming customerId is in column 0

        // Delete the customer from the database
        String deleteQuery = "DELETE FROM customer WHERE customerId = ?";
        try (Connection connection = DatabaseConnection.getConnection(); PreparedStatement statement = connection.prepareStatement(deleteQuery)) {

            statement.setInt(1, customerId);
            int rowsAffected = statement.executeUpdate();

            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Customer deleted successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                // Remove the row from the table model
                model.removeRow(selectedRow);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete the customer.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred while deleting the customer.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerMgm1;
    private javax.swing.JButton customerMgm2;
    private javax.swing.JButton customerMgm3;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
