package com.snapshop.form;

import com.snapshop.component.SelectedItem;
import com.snapshop.component.Item;
import com.snapshop.controller.PlatformController;
import com.snapshop.event.AddToCartListener;
import com.snapshop.event.EventItem;
import com.snapshop.model.ModelItem;
import com.snapshop.swing.ScrollBar;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author lucas
 */
public class FormHome extends javax.swing.JPanel {

    private EventItem event;
    private SelectedItem item;
    private Ads ad;
    private AddToCartListener addToCartListener;

    /**
     * @param event the event to set
     */
    public void setEvent(EventItem event) {
        this.event = event;
    }

    /**
     * Creates new form FormHome
     */
    public FormHome(AddToCartListener addToCartListener) {
        initComponents();
        scroll.setVerticalScrollBar(new ScrollBar());
        init();
        this.addToCartListener = addToCartListener;
    }

    private void init() {
        ad = new Ads();
        subPanel.setLayout(new BorderLayout());
        subPanel.add(ad);
    }

    public void addItem(ModelItem data) {
        Item item = new Item();
        item.setData(data);
        item.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                if (SwingUtilities.isLeftMouseButton(me)) {
                    event.itemClick(item, data);
                }
            }
        });
        panelItem.add(item);
        panelItem.repaint();
        panelItem.revalidate();
    }

    public void setSelected(Component item) {
        for (Component com : panelItem.getComponents()) {
            Item i = (Item) com;
            if (i.isSelected()) {
                i.setSelected(false);
            }
        }
        ((Item) item).setSelected(true);
    }

    public void showItem(ModelItem data) {
        // Remove all components from the subPanel
        subPanel.removeAll();

        // Create and add the new SelectedItem panel
        item = new SelectedItem(addToCartListener);
        item.setData(data);
        subPanel.add(item, BorderLayout.CENTER);

        // Revalidate and repaint the subPanel to reflect changes
        subPanel.revalidate();
        subPanel.repaint();
    }

    public void showAllItems() {
        panelItem.removeAll(); // Clear all current items

        // Fetch all items from the controller
        PlatformController controller = PlatformController.getInstance();
        List<ModelItem> items = controller.getAllItems();

        // Add each item to the UI
        for (ModelItem item : items) {
            addItem(item);
        }

        panelItem.repaint(); // Refresh the UI
        panelItem.revalidate();
    }

    public void filterItems(String column, String value) {
        panelItem.removeAll(); // Clear current items

        // Fetch filtered items from the controller
        PlatformController controller = PlatformController.getInstance();
        List<ModelItem> filteredItems = controller.getFilteredItems(column, value);

        // Add each filtered item to the UI
        for (ModelItem item : filteredItems) {
            addItem(item);
        }

        panelItem.repaint(); // Refresh the UI
        panelItem.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        panelItem = new com.snapshop.swing.PanelItem();
        subPanel = new javax.swing.JPanel();

        setOpaque(false);

        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setViewportView(panelItem);

        subPanel.setBackground(new java.awt.Color(255, 255, 255));
        subPanel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
            .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.snapshop.swing.PanelItem panelItem;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables
}
