package com.snapshop.form;

/**
 *
 * @author lucas
 */
public class FormHome extends javax.swing.JPanel {

    /**
     * Creates new form FormHome
     */
    public FormHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        panelItem = new com.snapshop.swing.PanelItem();
        item1 = new com.snapshop.component.Item();
        item2 = new com.snapshop.component.Item();
        item3 = new com.snapshop.component.Item();
        item4 = new com.snapshop.component.Item();
        item5 = new com.snapshop.component.Item();
        item6 = new com.snapshop.component.Item();
        item7 = new com.snapshop.component.Item();
        item8 = new com.snapshop.component.Item();
        item9 = new com.snapshop.component.Item();
        item10 = new com.snapshop.component.Item();

        setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCT");

        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelItem.add(item1);
        panelItem.add(item2);
        panelItem.add(item3);
        panelItem.add(item4);
        panelItem.add(item5);
        panelItem.add(item6);
        panelItem.add(item7);
        panelItem.add(item8);
        panelItem.add(item9);
        panelItem.add(item10);

        scroll.setViewportView(panelItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.snapshop.component.Item item1;
    private com.snapshop.component.Item item10;
    private com.snapshop.component.Item item2;
    private com.snapshop.component.Item item3;
    private com.snapshop.component.Item item4;
    private com.snapshop.component.Item item5;
    private com.snapshop.component.Item item6;
    private com.snapshop.component.Item item7;
    private com.snapshop.component.Item item8;
    private com.snapshop.component.Item item9;
    private javax.swing.JLabel jLabel2;
    private com.snapshop.swing.PanelItem panelItem;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
