/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.snapshop.form;

import com.snapshop.event.ShowCartListener;
import com.snapshop.swing.Background;
import javax.swing.JFrame;

/**
 *
 * @author lucas
 */
public class HomeHeader extends javax.swing.JPanel {

    private MyCart cart;
    private ShowCartListener listener;

    /**
     * Creates new form HomeHeader
     */
    public HomeHeader(JFrame fram, Background bg) {
        initComponents();
        winButton3.initEvent(fram, bg);
    }

    public void setShowCartListener(ShowCartListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        winButton3 = new com.snapshop.swing.win_button.WinButton();
        myCartBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1038, 75));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("SNAPSHOP MENUBAR");

        myCartBtn.setText("MY CART");
        myCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCartBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(winButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(28, 28, 28)
                .addComponent(myCartBtn)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(winButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(myCartBtn)
                        .addComponent(backBtn)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCartBtnActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.showCartPanel();
        } else {
            System.err.println("ShowCartListener is not set in HomeHeader.");
        }
    }//GEN-LAST:event_myCartBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.showHomePanel();
        } else {
            System.err.println("ShowCartListener is not set in HomeHeader.");
        }
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton myCartBtn;
    private com.snapshop.swing.win_button.WinButton winButton;
    private com.snapshop.swing.win_button.WinButton winButton1;
    private com.snapshop.swing.win_button.WinButton winButton3;
    // End of variables declaration//GEN-END:variables
}
