/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.snapshop.form;

import com.snapshop.form.Login;
import com.snapshop.controller.PlatformController;
import com.snapshop.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class StaffSignup extends javax.swing.JFrame {

    private PlatformController controller;

    /**
     * Creates new form SignUp
     */
    public StaffSignup() {
        controller = PlatformController.getInstance();
        initComponents();
        adminButton.setActionCommand("admin");
        associateButton.setActionCommand("associate");
        vendorButton.setActionCommand("vendor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signupButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        securityInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adminButton = new javax.swing.JRadioButton();
        associateButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        pwdInput = new javax.swing.JPasswordField();
        usernameInput = new javax.swing.JTextField();
        vendorButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel6.setFont(new java.awt.Font("SignPainter", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Snapshop");

        jLabel9.setFont(new java.awt.Font("SignPainter", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FOR STAFF ONLY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel6)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9)
                .addGap(116, 116, 116)
                .addComponent(jLabel6)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 500);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Username");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Password");

        signupButton.setBackground(new java.awt.Color(0, 153, 153));
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("Sign Up");
        signupButton.setBorderPainted(false);
        signupButton.setFocusPainted(false);
        signupButton.setOpaque(true);
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        goBackButton.setBackground(new java.awt.Color(102, 102, 102));
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setText("Back");
        goBackButton.setBorderPainted(false);
        goBackButton.setFocusPainted(false);
        goBackButton.setOpaque(true);
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        securityInput.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        securityInput.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Staff Type");

        roleGroup.add(adminButton);
        adminButton.setForeground(new java.awt.Color(102, 102, 102));
        adminButton.setText("Administrator");

        roleGroup.add(associateButton);
        associateButton.setForeground(new java.awt.Color(102, 102, 102));
        associateButton.setText("Associate");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Security Code");

        pwdInput.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        pwdInput.setForeground(new java.awt.Color(102, 102, 102));
        pwdInput.setPreferredSize(new java.awt.Dimension(64, 28));

        usernameInput.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        usernameInput.setForeground(new java.awt.Color(102, 102, 102));

        roleGroup.add(vendorButton);
        vendorButton.setForeground(new java.awt.Color(102, 102, 102));
        vendorButton.setText("Vendor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(usernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(pwdInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(adminButton)
                                .addGap(18, 18, 18)
                                .addComponent(associateButton)
                                .addGap(18, 18, 18)
                                .addComponent(vendorButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(securityInput, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButton)
                    .addComponent(associateButton)
                    .addComponent(vendorButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(pwdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(securityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // back to login interface
//        Login loginFrame = new Login();
//        loginFrame.setVisible(true);
//        loginFrame.pack();
//        loginFrame.setLocationRelativeTo(null);
//        this.dispose();
        Admin admin = new Admin(controller);
        admin.setVisible(true);
        admin.pack();
        admin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // Retrieve user inputs
        String username = usernameInput.getText().trim();
        String password = new String(pwdInput.getPassword()).trim();
        String securityCode = securityInput.getText().trim();
        // Retrieve the selected role from the ButtonGroup
        String role = null;
        if (roleGroup.getSelection() != null) {
            role = roleGroup.getSelection().getActionCommand();
        }

        StringBuilder errors = new StringBuilder();

        // Username validation
        if (username.isEmpty()) {
            errors.append("Username is required.\n");
        } else if (!username.matches("[a-zA-Z0-9]{3,50}")) { // Alphanumeric and 3-50 characters
            errors.append("Username should be 3-50 characters long and contain only letters and numbers.\n");
        }

        // Password validation
        if (password.isEmpty()) {
            errors.append("Password is required.\n");
        } else if (password.length() < 8) { // Minimum password length
            errors.append("Password should be at least 8 characters long.\n");
        }
//
        // security code validation
        if (securityCode.isEmpty()) {
            errors.append("security code is required for staff registration.\n");
        }

        // Role selection validation
        if (role == null || role.isEmpty()) {
            errors.append("Please select your role.\n");
        }

        // Display errors or proceed
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this, errors.toString(), "Input Validation Errors", JOptionPane.ERROR_MESSAGE);

        } else {
            // Call the registerCustomer method
            boolean success = controller.registerStaff(username, password, securityCode, role);

            if (success) {
//                Login loginFrame = new Login();
//                loginFrame.setVisible(true);
//                loginFrame.pack();
//                loginFrame.setLocationRelativeTo(null);
                Admin admin = new Admin(controller); 
               admin.setVisible(true);
                admin.pack();
                admin.setLocationRelativeTo(null);
                this.dispose();
            }
        }
    }//GEN-LAST:event_signupButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminButton;
    private javax.swing.JRadioButton associateButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pwdInput;
    private javax.swing.ButtonGroup roleGroup;
    private javax.swing.JTextField securityInput;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JRadioButton vendorButton;
    // End of variables declaration//GEN-END:variables
}
